---
name: Tests
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.version }}
      - name: Run tests
        run: |
          pnpm ci
          pnpm run test
